# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import is_allowed_descriptor_pb2 as proto_dot_is__allowed__descriptor__pb2


class IsAllowedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send = channel.unary_unary(
                '/com.example.nanay.gRPCServer.IsAllowedService/send',
                request_serializer=proto_dot_is__allowed__descriptor__pb2.IsAllowedRequest.SerializeToString,
                response_deserializer=proto_dot_is__allowed__descriptor__pb2.IsAllowedReply.FromString,
                )


class IsAllowedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IsAllowedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send': grpc.unary_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=proto_dot_is__allowed__descriptor__pb2.IsAllowedRequest.FromString,
                    response_serializer=proto_dot_is__allowed__descriptor__pb2.IsAllowedReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.example.nanay.gRPCServer.IsAllowedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IsAllowedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.example.nanay.gRPCServer.IsAllowedService/send',
            proto_dot_is__allowed__descriptor__pb2.IsAllowedRequest.SerializeToString,
            proto_dot_is__allowed__descriptor__pb2.IsAllowedReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
