# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/is_allowed_descriptor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/is_allowed_descriptor.proto\x12\x1c\x63om.example.nanay.gRPCServer\" \n\x10IsAllowedRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x0eIsAllowedReply\x12\x11\n\tisAllowed\x18\x01 \x01(\x08\x32z\n\x10IsAllowedService\x12\x66\n\x04send\x12..com.example.nanay.gRPCServer.IsAllowedRequest\x1a,.com.example.nanay.gRPCServer.IsAllowedReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.is_allowed_descriptor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ISALLOWEDREQUEST._serialized_start=67
  _ISALLOWEDREQUEST._serialized_end=99
  _ISALLOWEDREPLY._serialized_start=101
  _ISALLOWEDREPLY._serialized_end=136
  _ISALLOWEDSERVICE._serialized_start=138
  _ISALLOWEDSERVICE._serialized_end=260
# @@protoc_insertion_point(module_scope)
